ethereum: add tokens
digitalbitbox/bitbox02-firmware pull request #1024
Opened 2022-12-15 14:26 UTC by jadzeidan

added tokens "PRQ" and "METIS"

2022-12-21 13:49 UTC, benma requested changes

2022-12-21 13:49 UTC, benma commented on src/apps/eth/eth_params.c
> +            "\x36\x2b\xc8\x47\xA3\xa9\x63\x7d\x3a\xf6\x62\x4E\xeC\x85\x36\x18\xa4\x3e\xd7\xD2",
please lowercase all chars, same as all other addresses above

2022-12-21 13:49 UTC, benma commented on src/apps/eth/eth_params.c
> +            "\x9E\x32\xb1\x3c\xe7\xf2\xE8\x0A\x01\x93\x2B\x42\x55\x36\x52\xE0\x53\xD6\xed\x8e",
same

2023-01-04 09:32 UTC, jadzeidan commented
@benma I looked at the code again and realize PRQ and METIS are already in master. It seems the the tokens are not entirely in alphabetical order so I didn't notice them before. I will close the PR.

2023-01-04 09:32 UTC, closed without merging